
import type { LMCompatibilityEntry, LMRiskLevelKey, PregnancyCategory } from './types';

export const LM_RISK_LEVEL_INFO: Record<LMRiskLevelKey, { text: string; secondaryText: string; colorClass: string }> = {
  safe: { text: "Seguro, mejor opción", secondaryText: "Compatible.", colorClass: "text-green-600 dark:text-green-400" },
  quiteSafe: { text: "Bastante seguro", secondaryText: "Compatibilidad probable.", colorClass: "text-yellow-600 dark:text-yellow-400" },
  lessSafe: { text: "Poco seguro", secondaryText: "Compatibilidad limitada.", colorClass: "text-orange-600 dark:text-orange-500" },
  veryUnsafe: { text: "Muy inseguro", secondaryText: "Incompatible.", colorClass: "text-red-700 dark:text-red-600" },
};

export const PREGNANCY_CATEGORY_INFO: Record<PregnancyCategory, { text: string; description: string; colorClass: string }> = {
    A: { text: "Sin Riesgos Aparentes", description: "No hay evidencia de riesgo fetal. SE PUEDE UTILIZAR.", colorClass: "text-green-600 dark:text-green-400" },
    B: { text: "Sin Riesgos Aparentes", description: "No existen pruebas de riesgo en especie humana. PROBABLEMENTE SEGURO.", colorClass: "text-green-600 dark:text-green-400" },
    C: { text: "Riesgo no Detectable", description: "No se puede descartar la existencia de riesgo. UTILIZAR VALORANDO RELACIÓN BENEFICIO/RIESGO.", colorClass: "text-yellow-600 dark:text-yellow-400" },
    D: { text: "Riesgo Demostrado", description: "Existen pruebas de riesgo. Los beneficios potenciales pueden sobrepasar el riesgo. EVITARLOS SI EXISTE OTRA ALTERNATIVA.", colorClass: "text-orange-600 dark:text-orange-500" },
    X: { text: "Contraindicado", description: "Existe evidencia de riesgo fetal en el ser humano. El riesgo sobrepasa cualquier beneficio. CONTRAINDICADO.", colorClass: "text-red-700 dark:text-red-600" },
};

const allData: LMCompatibilityEntry[] = [
  // Seguro, mejor opción
  { id: 'amoxicilina', name: 'Amoxicilina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'amoxicilina-clavulanico', name: 'Amoxicilina-Clavulánico', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'ampicilina', name: 'Ampicilina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'ampicilina-sulbactam', name: 'Ampicilina-Sulbactam', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'cloxacilina', name: 'Cloxacilina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'flucloxacilina', name: 'Flucloxacilina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'penicilina-g', name: 'Penicilina G', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'penicilina-g-benzatina', name: 'Penicilina G Benzatina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'penicilina-sodica', name: 'Penicilina Sódica', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'piperacilina-tazobactam', name: 'Tazonam (Piperacilina-Tazobactam)', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'paracetamol', name: 'Paracetamol', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'sumatriptan', name: 'Sumatriptán', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'eletriptan', name: 'Eletriptán', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'tramadol', name: 'Tramadol', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'tetraciclina', name: 'Tetraciclina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'cefadroxilo', name: 'Cefadroxilo', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'cefazolina', name: 'Cefazolina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'cefepima', name: 'Cefepima', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'cefotaxima', name: 'Cefotaxima', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'ceftazidima', name: 'Ceftazidima', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'ceftriaxona', name: 'Ceftriaxona', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'cefuroxima', name: 'Cefuroxima', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'aztreonam', name: 'Aztreonam', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'meropenem', name: 'Meropenem', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'ertapenem', name: 'Ertapenem', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'imipenem-cilastatina', name: 'Imipenem + Cilastatina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'sulfametoxazol', name: 'Sulfametoxazol', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'trimetoprim', name: 'Trimetoprim', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'cotrimoxazol', name: 'Cotrimoxazol (Sulfametoxazol + Trimetoprim)', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'azitromicina', name: 'Azitromicina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'claritromicina', name: 'Claritromicina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'clindamicina', name: 'Clindamicina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'lincomicina', name: 'Lincomicina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'amikacina', name: 'Amikacina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'estreptomicina', name: 'Estreptomicina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'gentamicina', name: 'Gentamicina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'kanamicina', name: 'Kanamicina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'neomicina', name: 'Neomicina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'tobramicina', name: 'Tobramicina', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'ciprofloxacino', name: 'Ciprofloxacino', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'bacitracina', name: 'Bacitracina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'colistin', name: 'Colistín', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'fosfomicina', name: 'Fosfomicina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'metronidazol', name: 'Metronidazol', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'nitrofurantoina', name: 'Nitrofurantoína', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'polimixina-b', name: 'Polimixina B', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'tinidazol', name: 'Tinidazol', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'vancomicina', name: 'Vancomicina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'acido-fusidico', name: 'Ácido Fusídico', riskLevel: 'safe', pregnancyCategory: 'D' },
  { id: 'achicoria', name: 'Achicoria', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'adenosina-monofosfato-amp', name: 'Adenosina Monofosfato (AMP)', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'agua', name: 'Agua', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'agua-tonica', name: 'Agua tónica', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'ajo', name: 'Ajo', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'alcachofa', name: 'Alcachofa', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'algarrobo', name: 'Algarrobo', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'amaranto-kiwicha', name: 'Amaranto (kiwicha)', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'aminoacidos-cadena-ramificada-bcaas', name: 'Aminoácidos de cadena ramificada (BCAAs)', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'arginina', name: 'Arginina', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'azufaifo', name: 'Azufaifo', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'benzquercina', name: 'Benzquercina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'cebolla', name: 'Cebolla', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'chitosan', name: 'Chitosan', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'chumbera-nopal', name: 'Chumbera, nopal', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'chia', name: 'Chía', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'colageno', name: 'Colágeno', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'diente-de-leon', name: 'Diente de león', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'dieta-hipocalorica', name: 'Dieta hipocalórica', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'elagico-acido', name: 'Elágico, ácido', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'etoxazorutosido', name: 'Etoxazorutósido', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'flavodato-sodico', name: 'Flavodato sódico', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'flavonoides', name: 'Flavonoides', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'germen-de-trigo', name: 'Germen de trigo', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'glicofosfopeptical', name: 'Glicofosfopeptical', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'glucomanano', name: 'Glucomanano', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'glucosa', name: 'Glucosa', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'hesperidina', name: 'Hesperidina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'hibisco', name: 'Hibisco', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'inositol', name: 'Inositol', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'jalea-real', name: 'Jalea real', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'jarabe-de-arce-sirope-de-arce', name: 'Jarabe de arce, sirope de arce', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'kefir', name: 'Kéfir', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'lecitina', name: 'Lecitina', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'leucocianidol', name: 'Leucocianidol', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'levadura-de-cerveza', name: 'Levadura de cerveza', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'lisina', name: 'Lisina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'maca', name: 'Maca', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'manosa-d-manosa', name: 'Manosa, D-Manosa', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'mate-yerba-mate', name: 'Mate, Yerba Mate', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'metionina-l-metionina-dl-metionina', name: 'Metionina, L-Metionina, DL-Metionina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'monoxerutina', name: 'Monoxerutina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'moringa', name: 'Moringa', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'naranjo-amargo', name: 'Naranjo Amargo', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'nogal-nuez-nueces', name: 'Nogal, nuez, nueces', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'onagra', name: 'Onagra', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'pectina', name: 'Pectina', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'pina', name: 'Piña', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'prebioticos', name: 'Prebióticos', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'quercetina', name: 'Quercetina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'quinoa', name: 'Quinoa', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'raponchigo', name: 'Rapónchigo', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'resveratrol', name: 'Resveratrol', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'rutosido', name: 'Rutosido', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'rabano', name: 'Rábano', riskLevel: 'safe', pregnancyCategory: 'B' },
  { id: 'sesamo', name: 'Sésamo', riskLevel: 'safe', pregnancyCategory: 'A' },
  { id: 'teobromina', name: 'Teobromina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'troxerutina', name: 'Troxerutina', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'vid', name: 'Vid', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'acido-tanico-taninos', name: 'Ácido tánico, taninos', riskLevel: 'safe', pregnancyCategory: 'C' },
  { id: 'acidos-grasos-omega-3-dha-epa-ala', name: 'Ácidos grasos omega 3 (DHA, EPA, ALA)', riskLevel: 'safe', pregnancyCategory: 'A' },

  // Bastante seguro
  { id: 'meticilina', name: 'Meticilina', riskLevel: 'quiteSafe', pregnancyCategory: 'B' },
  { id: 'aspirina', name: 'Aspirina', riskLevel: 'quiteSafe', pregnancyCategory: 'D' },
  { id: 'clonixinato-lisina', name: 'Clonixinato de Lisina', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'clonidina', name: 'Clonidina', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'morfina', name: 'Morfina', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'petidina', name: 'Petidina', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'doxiciclina', name: 'Doxiciclina', riskLevel: 'quiteSafe', pregnancyCategory: 'D' },
  { id: 'eritromicina', name: 'Eritromicina', riskLevel: 'quiteSafe', pregnancyCategory: 'B' },
  { id: 'enoxacino', name: 'Enoxacino', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'gatifloxacino', name: 'Gatifloxacino', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'levofloxacino', name: 'Levofloxacino', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'acido-nalidixico', name: 'Ácido Nalidíxico', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },
  { id: 'linezolid', name: 'Linezolid', riskLevel: 'quiteSafe', pregnancyCategory: 'C' },

  // Poco seguro
  { id: 'metamizol', name: 'Metamizol', riskLevel: 'lessSafe', pregnancyCategory: 'D' },
  { id: 'ergotamina-tartrato', name: 'Ergotamina tartrato', riskLevel: 'lessSafe', pregnancyCategory: 'X' },
  { id: 'codeina', name: 'Codeína', riskLevel: 'lessSafe', pregnancyCategory: 'C' },
  { id: 'oxicodona', name: 'Oxicodona', riskLevel: 'lessSafe', pregnancyCategory: 'B' },
  { id: 'cloranfenicol-sistemico', name: 'Cloranfenicol (uso sistémico)', riskLevel: 'lessSafe', pregnancyCategory: 'C' },
];


export const LM_COMPATIBILITY_DATA: LMCompatibilityEntry[] = [...new Set(allData.map(item => item.id))]
  .map(id => allData.find(item => item.id === id)!)
  .sort((a, b) => a.name.localeCompare(b.name));
